### ISSUE TITLE
DateFormat parsing 24hr time fails if hour is 00

### ISSUE THREAD

**Issue by mark1010** [dart-lang/intl#101]
```
final DateFormat df = new DateFormat('HH:mm');
DateTime dt = df.parseStrict("00:00");
print('$dt');
```

```
Unhandled exception:
FormatException: Error parsing 00:00, invalid hour value: 0
```

**Comment by alan-knight** [comment]
This doesn't reproduce for me in either the VM or JS. Can you provide more details.

1970-01-01 00:00:00.000

**Comment by mark1010** [comment]
initially filed with Dart VM version: 1.14.0-dev.5.0 (Fri Dec 18 02:14:17 2015) on "macos_x64"

this entry, Dart VM version: 1.14.0-dev.6.0 (Wed Jan  6 01:57:16 2016) on "macos_x64"
intl, version: “0.12.5"

I appreciate that parsing just the hour / minute may not be the intended use of the api. I flagged it principally due the inconsistency you’ll see below, it fails only on 00:00.

```
main() {
  final DateFormat df = new DateFormat('HH:mm');
  var nf = new NumberFormat("00");
  for(int n=23;n>=0;n--) {
    var hour = nf.format(n);
    var ts  = "$hour:00";
    print(ts);
    DateTime dt = df.parseStrict(ts);
    print('$dt');
  }
}
```
output:
```
23:00
1970-01-01 23:00:00.000
22:00
1970-01-01 22:00:00.000
21:00
1970-01-01 21:00:00.000
20:00
1970-01-01 20:00:00.000
19:00
1970-01-01 19:00:00.000
18:00
1970-01-01 18:00:00.000
17:00
1970-01-01 17:00:00.000
16:00
1970-01-01 16:00:00.000
15:00
1970-01-01 15:00:00.000
14:00
1970-01-01 14:00:00.000
13:00
1970-01-01 13:00:00.000
12:00
1970-01-01 12:00:00.000
11:00
1970-01-01 11:00:00.000
10:00
1970-01-01 10:00:00.000
09:00
1970-01-01 09:00:00.000
08:00
1970-01-01 08:00:00.000
07:00
1970-01-01 07:00:00.000
06:00
1970-01-01 06:00:00.000
05:00
1970-01-01 05:00:00.000
04:00
1970-01-01 04:00:00.000
03:00
1970-01-01 03:00:00.000
02:00
1970-01-01 02:00:00.000
01:00
1970-01-01 01:00:00.000
00:00
Unhandled exception:
FormatException: Error parsing 00:00, invalid hour value: 0
#0      _DateBuilder._verify (package:intl/src/intl/date_format_helpers.dart:74:7)
#1      _DateBuilder.verify (package:intl/src/intl/date_format_helpers.dart:67:5)
#2      DateFormat._parse (package:intl/src/intl/date_format.dart:351:28)
#3      DateFormat.parseStrict (package:intl/src/intl/date_format.dart:338:7)
#4      main (file:///.../test_datetime.dart:22:22)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alan-knight** [comment]
In bleeding edge 1.14, this works fine for me, on macos_x64. I'm not sure why you're seeing this.

The line in question is attempting to validate that hour24 agrees with the created DateTime's value. Can you get a debugger on that and see what the DateTime looks like?

**Comment by alan-knight** [comment]
Ah, this is an SDK bug from https://github.com/dart-lang/sdk/issues/19923 which we really can't do much about. A workaround is to do something like prepend a year and then parse in a format that expects a year as well. If it's not trying to parse to 1970 it should be fine.
