### ISSUE TITLE
intl_translation:extract_to_arb should support const references as name

### ISSUE THREAD

**Issue by zoechi** [dart-lang/intl#175]
```dart
  String themeDisplayName(String themeName) {
    switch (themeName) {
      case 'origin':
        return Intl.message('Origin', name: AppTheme.origin.name);
      case 'purple':
        return Intl.message('Purple', name: AppTheme.purple.name);
    ...
```
To make refactoring easier and prevent accidental mismatches.

**used constants**
```dart
class AppTheme {
  static const AppTheme origin = const AppTheme('origin');
  static const AppTheme purple = const AppTheme('purple');
  ...

  final String name;
}
```

Currently I get
```
Skipping invalid Intl.message invocation
    <Intl.message('Origin', name: AppTheme.origin.name)>
    reason: The 'name' argument for Intl.message must be a string literal
    from File: 'lib/localization/localizations.dart'    line: 33, column: 16
Skipping invalid Intl.message invocation
    <Intl.message('Purple', name: AppTheme.purple.name)>
    reason: The 'name' argument for Intl.message must be a string literal
    from File: 'lib/localization/localizations.dart'    line: 35, column: 16
```

**Comment by alan-knight** [comment]
I think it would be better to do that as an Intl.select rather than a bunch of messages anyway, which would reduce the problem. 

Also, for a message with no parameters, you can omit the name entirely.

In general, I think we're unlikely to do this, because it would make the message extraction significantly more complex and slower. Right now it's purely syntactic, and we don't resolve names at all.

**Comment by zoechi** [comment]
Thanks for the hint with `select`. I wasn't aware of that.

I tried
```
String themeName(String name) => Intl.select(
        name,
        <String, String>{
          AppTheme.origin.name: 'Origin',
          AppTheme.purple.name: 'Purple',
          AppTheme.blue.name: 'Blue',
          AppTheme.lightBlue.name: 'Light Blue',
          AppTheme.dark.name: 'Dark',
          AppTheme.orange.name: 'Orange',
          AppTheme.brown.name: 'Brown',
          AppTheme.pink.name: 'Pink',
          AppTheme.blueGray.name: 'Blue Gray',
          AppTheme.green.name: 'Green',
        },
        name: 'themeName',
        desc: 'The names of UI themes',
//        args: <String>[name],
      ); 
```
which caused
```
  flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/localization/localizations.dart
  Skipping invalid Intl.message invocation
      <Intl.select(name, <String, String> {AppTheme.origin.name : 'Origin', AppTheme.purple.name : 'Purple', AppTheme.blue.name : 'Blue', AppTheme.lightBlue.name : 'Light Blue', AppTheme.dark.name : 'Dark', AppTheme.orange.name : 'Orange', AppTheme.brown.name : 'Brown', AppTheme.pink.name : 'Pink', AppTheme.blueGray.name : 'Blue Gray', AppTheme.green.name : 'Green'}, name: 'themeName', desc: 'The names of UI themes')>
      reason: The 'args' argument for Intl.message must be specified for messages with parameters. Consider using rewrite_intl_messages.dart
      from lib/localization/localizations.dart    line: 29, column: 36
```

when I comment in the `args: [name]` line I get

```
  Skipping invalid Intl.message invocation
      <Intl.select(name, <String, String> {AppTheme.origin.name : 'Origin', AppTheme.purple.name : 'Purple', AppTheme.blue.name : 'Blue', AppTheme.lightBlue.name : 'Light Blue', AppTheme.dark.name : 'Dark', AppTheme.orange.name : 'Orange', AppTheme.brown.name : 'Brown', AppTheme.pink.name : 'Pink', AppTheme.blueGray.name : 'Blue Gray', AppTheme.green.name : 'Green'}, name: 'themeName', desc: 'The names of UI themes', args: <String> [name])>
      reason: Unexpected exception: NoSuchMethodError: Class 'PropertyAccessImpl' has no instance getter 'value'.
  Receiver: Instance of 'PropertyAccessImpl'
  Tried calling: value, #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
  #1      Select.argumentsOfInterestFor.<anonymous closure> (package:intl_translation/src/intl_message.dart:904)
  #2      MapBase._fillMapWithMappedIterable (dart:collection/maps.dart:67)
  #3      new LinkedHashMap.fromIterable (dart:collection/linked_hash_map.dart:124)
  #4      Select.argumentsOfInterestFor (package:intl_translation/src/intl_message.dart:903)
  #5      PluralAndGenderVisitor.messageFromMethodInvocation (package:intl_translation/extract_messages.dart:590)
  #6      PluralAndGenderVisitor.visitMethodInvocation (package:intl_translation/extract_messages.dart:545)
  #7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
  #8      MessageFindingVisitor.messageFromDirectPluralOrGenderCall.extractFromPluralOrGender (package:intl_translation/extract_messages.dart:428)
  #9      MessageFindingVisitor._messageFromNode (package:intl_translation/extract_messages.dart:341)
  #10     MessageFindingVisitor.messageFromDirectPluralOrGenderCall (package:intl_translation/extract_messages.dart:438)
  #11     MessageFindingVisitor._extractMessage (package:intl_translation/extract_messages.dart:285)
  #12     MessageFindingVisitor.addIntlMessage (package:intl_translation/extract_messages.dart:260)
  #13     MessageFindingVisitor.visitMethodInvocation (package:intl_translation/extract_messages.dart:249)
  #14     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
  #15     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4108)
  #16     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
  #17     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
  #18     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:288)
  #19     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4104)
  #20     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7759)
  #21     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
  #22     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:156)
  #23     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:247)
  #24     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:205)
  #25     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:409)
  #26     MessageFindingVisitor.visitMethodDeclaration (package:intl_translation/extract_messages.dart:197)
  #27     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7750)
  #28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
  #29     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1982)
  #30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
  #31     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:156)
  #32     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:247)
  #33     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:222)
  #34     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:416)
  #35     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:203)
  #36     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1914)
  #37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
  #38     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2511)
  #39     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
  #40     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:219)
  #41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
  #42     MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:82)
  #43     main (file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.16.8/bin/extract_to_arb.dart:71)
  #44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
  #45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
  
      from lib/localization/localizations.dart    line: 29, column: 36
```

**Comment by zoechi** [comment]
Ups, need to use literal strings here as well.

**Comment by alan-knight** [comment]
Yes, was just responding. We don't resolve anything, so we can't deal with non-literals.

**Comment by zoechi** [comment]
Why do I need to pass `args` if I don't use it?

**Comment by alan-knight** [comment]
What happens at runtime is that it looks up the locale and forwards to another function. It needs to know what the arguments are, and we don't have enough reflection to do it automatically. With transformers we could do that behind the scenes, but not any more.

**Comment by ashour** [comment]
Hey, if the intl_translation transformer won't include the args for you, then is the https://pub.dartlang.org/packages/intl documentation page out of date? Could we update it if it is?

**Comment by alan-knight** [comment]
Transformers are no longer supported at all, so yes, that's out of date and should be updated.

**Comment by ashour** [comment]
Noted. Btw I used the intl_translate transformer to successfully omit the `name` param when building simple `Intl.message`s. I was using intl 0.15.7 and intl_translation 0.17.0. Not sure if you dropped support in master and if it's coming up in a future version, but wanted to let you know that transformers still do work.

**Comment by alan-knight** [comment]
More that transformers in general go away with Dart 2. It's unfortunate in some ways, because they let us do things like this that are much more awkward to do in other ways. But they also had significant issues, the new build system doesn't support them at all.

**Comment by supermuka** [comment]
What must be done not to have this error?

**error**:
> Error IntlMessageExtractionException: Invalid select keyword: 'Objectives and Works', must match '[a-zA-Z][a-zA-Z0-9_-]*'
> Processing <Intl.select(label, {'AUGE' : 'AUGE', 'Objectives and Works' : 'Objectives and Works', 'Search' : 'Search', 'Filter' : 'Filter', 'more' : 'more', 'empty' : 'empty', 'other' : 'Not Defined'})>    from lib/shared/message/messages.dart    line: 9, column: 12
> Skipping invalid Intl.message invocation
>     <Intl.message('''${Intl.select(label, {'AUGE' : 'AUGE', 'Objectives and Works' : 'Objectives and Works', 'Search' : 'Search', 'Filter' : 'Filter', 'more' : 'more', 'empty' : 'empty', 'other' : 'Not Defined'})}''', name: "label", args: [label], desc: "Common labels
> ", examples: const {"AUGE" : "Auge"})>
>     reason: Unexpected exception: NoSuchMethodError: The setter 'mainArgument=' was called on null.
> Receiver: null
> Tried calling: mainArgument="label", #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)

**command**:
`pub run intl_translation:extract_to_arb --output-dir=lib/shared/message/i18n lib/shared/message/messages.dart`


**code**:
```
  static label(String label) => Intl.message(
      '${Intl.select(label, {
        'AUGE': 'AUGE',
        'Objectives and Works': 'Objectives and Works',
        'Search': 'Search',
        'Filter': 'Filter',
        'more': 'more',
        'empty': 'empty',
        'other': 'Not Defined'})}',
      name: "label",
      args: [label],
      // locale: "en",
      desc: "Common labels",
      examples: const {"AUGE": "AUGE"}
  );
```

**Comment by alan-knight** [comment]
What it says, have the select keywords match the allowable Regex. So 'Objectives and Works' would have to be changed to something like 'objectives_and_works'. That restrictions is there because the initial translation tool we wrote against had that restriction. Others may not, so it could possibly be removed. But the workaround is that you would need to transform any strings that didn't match.

Also, you have a redundant layer of quoting in there, and I think your arguments are being passed at the wrong level. And the examples is a map from argument names. So what you'd want is

```
 static label(String label) => Intl.select(label, {
        'AUGE': 'AUGE',
        'Objectives_and_Works': 'Objectives and Works',
        'Search': 'Search',
        'Filter': 'Filter',
        'more': 'more',
        'empty': 'empty',
        'other': 'Not Defined'})},
      name: "label",
      args: [label],
      // locale: "en",
      desc: "Common labels",
      examples: const {"label": "AUGE"}
  );
```
