### ISSUE TITLE
How to escape curly brace in arb file?

### ISSUE THREAD

**Issue by Gerrel** [dart-lang/intl#217]
I'm trying to escape the word {test} in the .arb file.

// dart file
```dart
Intl.message(
        "{test}",
        name: "flutter_test",
        args: []);
```
---
//1. intl_en.arb
```json
{
"flutter_test": "{test}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "{test}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
Invalid argument(s)
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
```

---
//2. intl_en.arb
```json
{
  "flutter_test": "\{test\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\{test\}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
FormatException: Unrecognized string escape (at line 2, character 22)
  "flutter_test": "\{test\}",
                     ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
```
---
//3. intl_en.arb
```json
{
  "flutter_test": "\\{test\\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\\{test\\}"
  },
"@@locale": "nl"
}
```
Does not give a error, but shows the result \\{test\\}. ([slash][curly-brace]test[slash][curly-brace])

How to do a proper escape of a curly brace?

**Comment by alan-knight** [comment]
The answer is quite non-obvious, I had to look at the grammar to find it, but I believe that

      '{'test'}'

should work. JSON escapes won't help, because the problem is not JSON mangling it, but the message format reader. See https://github.com/dart-lang/intl_translation/blob/master/lib/src/icu_parser.dart#L35

**Comment by Gerrel** [comment]
@alan-knight No success...

//4. intl_en.arb
```
{
  "flutter_test": "'{'test'}'",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "'{'test'}'"
  },
"@@locale": "en"
}
```
Does not give a error, but shows the result '{'test'}'. ([quote][curly-brace][quote]test[quote][curly-brace][quote])

**Comment by alan-knight** [comment]
Hmmm. It seems like that bit of grammar might only be used for messages that actually have placeholders. This might require a little work. You can work around it, I think, if the text inside the placeholder isn't a valid identifier. But that may not be possible. Or (ugh) you could make one of the curly braces an optional parameter and give it a default value and actually put it in a placeholder.
