### ISSUE TITLE
Process finished with exit code 2

### ISSUE THREAD

**Issue by ahmetozcan9211** [dart-lang/intl#267]
i cant generate locale files 
here is my 
`flutter --no-color pub global run intl_utils:generate`
command output is below

```
INFO: No @@locale or _locale field found in intl_ar, assuming 'ar' based on the file name.
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_es, assuming 'es' based on the file name.
INFO: No @@locale or _locale field found in intl_ja, assuming 'ja' based on the file name.
INFO: No @@locale or _locale field found in intl_tr, assuming 'tr' based on the file name.
ERROR: Failed to generate localization files.
pub finished with exit code 2
Process finished with exit code 2
```

and here is with verbose
`flutter --no-color pub global run intl_utils:generate -v`

```
INFO: No @@locale or _locale field found in intl_ar, assuming 'ar' based on the file name.
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_es, assuming 'es' based on the file name.
INFO: No @@locale or _locale field found in intl_ja, assuming 'ja' based on the file name.
INFO: No @@locale or _locale field found in intl_tr, assuming 'tr' based on the file name.
ERROR: Failed to generate localization files.
pub finished with exit code 2

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
and` flutter doctor -v` output

```
C:\Users\4ahme\Desktop\1\source>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.356], locale tr-TR)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\4ahme\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\4ahme\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by amolshinde07** [comment]
Add locale at the start of each file for ex. "@@locale":"en", below  is the full example.


{
   "@@locale":"mr",
  "@@last_modified": "2020-06-01T18:42:08.325594",
  "title": "inciar sesion",
  "@title": {
    "description": "Title for the Demo application",
    "type": "text",
    "placeholders": {}
  },
  "message": "Hola Mundo",
  "@message": {
    "description": "Message for the Demo application",
    "type": "text",
    "placeholders": {}
  }
}
}

**Comment by lzoran** [comment]
Better error handling is added in the [intl_utils 1.6.1](https://github.com/localizely/intl_utils/blob/master/CHANGELOG.md).
In the case that this error is still reproducible with the latest version of the `intl_utils` package, then it would be helpful to open a new issue on the [intl_utils](https://github.com/localizely/intl_utils) repo.

**Comment by ousvat** [comment]
I have the same issue

**Comment by ToniTornado** [comment]
I also got a similar error like yours after messing around with my locales.

```
ERROR: Failed to generate localization files. RangeError (end) [...]
pub finished with exit code 2
Process finished with exit code 2
```

Deleting the "generated" folder and regenerating the files finally fixed it for me.

**Comment by mosuem** [comment]
While there seems to be a [workaround](https://github.com/dart-lang/intl/issues/267#issuecomment-1288211474), this should still be fixed.
