### ISSUE TITLE
Intl Invalid locale 'null' IOS

### ISSUE THREAD

**Issue by illiashvedov** [dart-lang/intl#287]
### flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale ru)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (2 available)
```

ios (13.4.1 (17E262)) exception 

```
Non-fatal Exception: Invalid argument(s): Invalid locale 'null'
0  ???                            0x0 _throwLocaleError + 245 (intl.dart:245)
1  ???                            0x0 verifiedLocale + 239 (intl.dart:239)
2  ???                            0x0 new + 246 (date_format.dart:246)
3  ???                            0x0 _dateFormat + 16 (home_screen.dart:16)
4  ???                            0x0 build + 153 (home_screen.dart:153)
5  ???                            0x0 build + 4334 (framework.dart:4334)
6  ???                            0x0 performRebuild + 4223 (framework.dart:4223)
7  ???                            0x0 rebuild + 3947 (framework.dart:3947)
8  ???                            0x0 buildScope + 2432 (framework.dart:2432)
9  ???                            0x0 drawFrame + 773 (binding.dart:773)
10 ???                            0x0 _handlePersistentFrameCallback + 283 (binding.dart:283)
11 ???                            0x0 _invokeFrameCallback + 1102 (binding.dart:1102)
12 ???                            0x0 handleDrawFrame + 1041 (binding.dart:1041)
13 ???                            0x0 _handleDrawFrame + 957 (binding.dart:957)
```

**Comment by vHanda** [comment]
Hi. I'm on the exact same Flutter version -

```
flutter: The following ArgumentError was thrown building GitHostSetupRepoSelector(dirty, state:
flutter: GitHostSetupRepoSelectorState#9c5cd):
flutter: Invalid argument(s): Invalid locale "null"
flutter:
flutter: The relevant error-causing widget was:
flutter:   GitHostSetupRepoSelector file:///Users/vishesh/src/journal/lib/setup/screens.dart:239:16
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Intl._throwLocaleError (package:intl/intl.dart:245:5)
flutter: #1      Intl.verifiedLocale (package:intl/intl.dart:239:21)
flutter: #2      Intl.verifiedLocale (package:intl/intl.dart:224:14)
flutter: #3      new DateFormat (package:intl/src/intl/date_format.dart:249:20)
flutter: #4      GitHostSetupRepoSelectorState._buildRepoTile (package:gitjournal/setup/repo_selector.dart:192:25)
flutter: #5      GitHostSetupRepoSelectorState.build (package:gitjournal/setup/repo_selector.dart:129:41)
flutter: #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
flutter: #8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
flutter: #12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #19     _invoke (dart:ui/hooks.dart:261:10)
flutter: #20     _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 3 frames from dart:async)
```

The relevant code which causes this problem -
`    final _dateFormat = DateFormat('dd MMM, yyyy'); `

I've even tried calling `initializeDateFormatting()` from the `intl` package, but I still get this error.

**Comment by vHanda** [comment]
I found a workaround - 

https://github.com/GitJournal/GitJournal/commit/cd9d128b47ed523036f7ae1232ec7adcf04ed8a9

**Comment by mosuem** [comment]
This seems to be more of an issue with `package:gitjournal`, or am I missing something?
