### ISSUE TITLE
Can't parse negative NumberFormat

### ISSUE THREAD

**Issue by tsteward** [dart-lang/intl#293]
I am trying to parse a negative number using a financial number format
```dart
import 'package:intl/intl.dart';

void main(List<String> arguments) {
  var format = NumberFormat('#,##0.00;(#,##0.00)');
  print(format.parse('(3.22)'));
}
```
I get the following exception.
```
Unhandled exception:
FormatException: Invalid Number: (3.22)
#0      _NumberParser.invalidNumber (package:intl/src/intl/number_format.dart:1181:7)
#1      _NumberParser.parse (package:intl/src/intl/number_format.dart:1174:25)
#2      new _NumberParser (package:intl/src/intl/number_format.dart:1034:13)
#3      NumberFormat.parse (package:intl/src/intl/number_format.dart:597:29)
#4      main (file:///c/Users/tstew/projects/temp/intl_bug/bin/intl_bug.dart:5:16)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by alan-knight** [comment]
I think this is unlikely to work. Intl's number parsing recognizes negative numbers based on the the locale.MINUS_SIGN field. You might be able to mess around with it enough to get it to work, but it seems fragile. And parsing things that don't vary by locale is not a great use of intl. It's a lot slower, and is likely to fail unexpectedly if run in a different locale.

**Comment by mosuem** [comment]
Why use the parentheses around the number?
```
var format = NumberFormat('#,##0.00;(#,##0.00)');
print(format.parse('3.22'));
print(format.parse('-3.22'));
```
Works fine.
