### ISSUE TITLE
negative currency parsing not working for de_DE, but for de_AT

### ISSUE THREAD

**Issue by Freundschaft** [dart-lang/intl#295]
I have following code:

```
import 'package:intl/intl.dart';

void main() {
  final currencyFormatter = NumberFormat.currency(locale: "de_DE", symbol: "", decimalDigits: 2);
  print (currencyFormatter.parse('-10'));
}
```

as far as I can see, the formatter should be able to work with negative values. I expect the formatter to parse the value.

Instead I get this:

```
Unhandled exception:
FormatException: Invalid Number: -10
#0      _NumberParser.invalidNumber (package:intl/src/intl/number_format.dart:1181:7)
#1      _NumberParser.parse (package:intl/src/intl/number_format.dart:1173:44)
#2      new _NumberParser (package:intl/src/intl/number_format.dart:1034:13)
#3      NumberFormat.parse (package:intl/src/intl/number_format.dart:597:29)
#4      main (file:///C:/Users/qiong/Desktop/test/test.dart:6:28)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I step debugged into this, and it seems that the culprit lies here:
https://github.com/dart-lang/intl/blob/master/lib/src/intl/number_format.dart#L1172

Apparently the negativeSuffix for de_DE is somehow an empty space character, which is of course wrong, and causes the NumberFormatter to throw an error.

Out of curiosity I changed the locale from de_DE to en_US and then parsing works!, more interestingly it also works when I change the locale to de_AT.

There must be an oversight somewhere in the locale configuration, causing the negativeSuffix to be set incorrectly for the locale de_DE

Can someone check?

**Comment by romatallinn** [comment]
It seems the issue is relevant for all countries with the euro currency since they all share currency pattern. Moreover, I found `ru` locale also to fail under these conditions.

**Comment by Freundschaft** [comment]
yes indeed, generally .parse works very unreliably

**Comment by mosuem** [comment]
Closing in favor of #376 and #478.

The problem is the space inserted by the formatter: even if you try to avoid the `symbol` by setting it to an empty string, an unbreakable space will still be inserted.
This works:
```
final formatter = NumberFormat.currency(
  locale: "de_DE",
  symbol: "",
  decimalDigits: 2,
);
print(formatter.parse('-10\u00A0'));
```
Your second problem is simply the broken relationship between `format` and `parse` for currencies.
