### ISSUE TITLE
Intl.select "other" case requirement inconsistency

### ISSUE THREAD

**Issue by koral--** [dart-lang/intl#343]
Issue is the same as https://github.com/flutter/flutter/issues/70556 crossposting here according to https://github.com/flutter/flutter/issues/70556#issuecomment-727944361

Docs at https://api.flutter.dev/flutter/intl/Intl/select.html say:
> We look up the value of choice in cases and return the result, or an empty string if it is not found.

However in fact the following exception is thrown when value not matching any case is passed:

```
Invalid argument(s): The 'other' case must be specified
When the exception was thrown, this was the stack: 
#0      Intl.selectLogic (package:intl/intl.dart:552:7)
#1      Intl._select (package:intl/intl.dart:533:26)
#2      Intl.select (package:intl/intl.dart:517:12)
```

Code reproducing this issue:
```dart
print(Intl.select(
      'foo',
      {
        'bar': 'bar',
        'baz': 'baz',
      },
      args: ['foo'],
    ));
```

```
$ flutter --version
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (2 weeks ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

**Comment by YowFung** [comment]
Same issue. 
@koral-- Have you solved it?

**Comment by koral--** [comment]
No, @TahaTesser have also not responded what is the correct place to report this.

**Comment by mosuem** [comment]
This is an error with the documentation - indeed the `other` case must always be specified, as per the [ICU specs](https://unicode-org.github.io/icu/userguide/format_parse/messages/).
