### ISSUE TITLE
DateFormat.jm().parse failed in signed and enterprise build

### ISSUE THREAD

**Issue by mehtahardikr** [dart-lang/intl#398]
`DateTime date =DateFormat("hh:mm a").parse('10:00 AM');`

```
Unhandled Exception: FormatException: Trying to read   from 10:00 at position 6
    #0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:86)
    #1      _DateFormatField.parseLiteral (package:intl/src/intl/date_format_field.dart:55)
    #2      _DateFormatQuotedField.parse (package:intl/src/intl/date_format_field.dart:118)
    #3      DateFormat._parse (package:intl/src/intl/date_format.dart:394)
    #4      DateFormat.parse (package:intl/src/intl/date_format.dart:325)
```

**Comment by lordvidex** [comment]
The value you are trying to parse doesn't follow the format defined. You could solve this issue like this:
```dart
1. DateTime date = DateFormat('hh:mm a').parse('10:00 AM');  // 'a' stands for am/pm marker 
2. DateTime date = DateFormat('hh:mm').parse('10:00'); // remove the am/pm marker altogether
```
