### ISSUE TITLE
Problem with parsing timestamp

### ISSUE THREAD

**Issue by eximius313** [dart-lang/intl#452]
Given such code:
```
void main(List<String> args) {
  var timestamp = "2022.01.13 23:23:59";
  var result = DateFormat('yyyy.MM.dd HH:mm:ss').parse(timestamp);
  print(result);
}
```
produces expected output, but this code:
```
void main(List<String> args) {
  var timestamp2 = "20220113232359";
  var result2 = DateFormat('yyyyMMddHHmmss').parse(timestamp2);
  print(result2);
}
```
produces exception:
```
FormatException: Trying to read MM from 20220113232359 at position 14
#0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:86:5)
#1      _DateFormatPatternField.parseField (package:intl/src/intl/date_format_field.dart:336:7)
#2      _DateFormatPatternField.parse (package:intl/src/intl/date_format_field.dart:249:5)
#3      DateFormat._parse (package:intl/src/intl/date_format.dart:394:13)
#4      DateFormat.parse (package:intl/src/intl/date_format.dart:325:7)
#5      main (package:test/test.dart:5:46)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

could you please fix it?

**Comment by natebosch** [comment]
closing in favor of #210
