### ISSUE TITLE
Invalid Number error when parsing correct currency number

### ISSUE THREAD

**Issue by wheeOs** [dart-lang/intl#478]
```dart
final formatter = NumberFormat.currency(locale: 'de', symbol: '€', customPattern: '#,##0.00 \u00A4');
const expectedString = '463,00 €';
const expectedNumber = 463.00;
print(formatter.format(463.00) == expectedString); // prints true
print(formatter.parse(expectedString) == expectedNumber); // ERROR
```

```
Invalid Number: 463,00 €

When the exception was thrown, this was the stack: 
#0      NumberParser.invalidNumber (package:intl/src/intl/number_parser.dart:217:7)
#1      NumberParser.parse (package:intl/src/intl/number_parser.dart:210:25)
```

**Comment by mosuem** [comment]
Similar to #442. the `NumberFormat.parse` functionality does not work as expected. Here, the error is thrown as the `'€'` symbol is not expected, only number characters are. In particular, the parser seems to have only a distant relationship with the `NumberFormat` which was input in the constructor.
