### ISSUE TITLE
initializeDateFormatting and Material delegate conflicting on tests

### ISSUE THREAD

**Issue by lubritto** [dart-lang/intl#493]
Hello, we were working on some test cases here and found an interesting conflict between the `initializeDateFormatting` helper and the MaterialApp delegate `util.loadDateIntlDataIfNotLoaded()`. If in our tests file we have a unit test case using the `initializeDateFormatting` and right after this case, we create another widgetTest the test fails due to a conflict.

Example:
``` dart
Future main() async {
  test("Unit test example", () async {
    initializeDateFormatting('en', null);
    //... code test
  });

  testWidgets("Widget test example", (WidgetTester tester) async {
    // Arrange
    await tester.pumpWidget(const MaterialApp(
      locale: Locale('en'),
      localizationsDelegates: L10n.localizationsDelegates,
      supportedLocales: L10n.supportedLocales,
      home: Text('test'),
    ));
    await tester.pumpAndSettle();
  });
}
```

This error is being returned
```
When the exception was thrown, this was the stack:
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
#1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
#2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:25:33)
#3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#5      CastMap.forEach (dart:_internal/cast.dart:287:13)
#6      loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/utils/date_localizations.dart:21:8)
#7      _MaterialLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:728:12)
```

After digging down on it we found the cause, it seems that inside the `initializeDateFormatting` it's loading the date patterns with this map `dateTimePatternMap()` which is a const. And when Material calls the `loadDateIntlDataIfNotLoaded` it's trying to update the map with a new value, but the map is a constant.

One way to avoid it is splitting the unit and widget tests into 2 diff files, but I believe this shouldn't be necessary since the Flutter tests framework allows us to have mixed tests on the same file. I would like to get your feedback about it and see how we can work from our side to improve it if necessary.

**Comment by alanknight-wk** [comment]
Yeah, this is a symptom that initializeDateFormatting sets an unmodifiable map (I think the system is what makes it unmodifiable, rather than the code, which predates such things). So if you want to use the custom initialization you have to start with a custom initialization. It ought to be fairly easy to fix.
