### ISSUE TITLE
Output dir not created with intl:generate_from_arb

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/intl#86]
If the value in output-dir is specified to a directory that is not present then the script fails.

```
C:\Users\eolmstead\Documents\GitHub\intl_test>pub run intl:generate_from_arb --output-dir=lib\src lib\sample_with_messages.dart intl_messages.arb
Unhandled exception:
FileSystemException: Cannot open file, path = 'lib\src\messages_messages.dart' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:531)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:555)
#4      generateIndividualMessageFile (package:intl/generate_localized.dart:148)
#5      generateLocaleFile (http://localhost:55453/generate_from_arb.dart:114)
#6      main (http://localhost:55453/generate_from_arb.dart:76)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by donny-dont** [comment]
Something like this would work

```
/// Creates a directory at the given [path].
Future<Null> createDirectory(String path) async {
  var directory = new Directory(path);

  if (!await directory.exists()) {
    _logger.fine('Creating directory at $path');
    directory.create(recursive: true);
  }
}
```
